# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        articles_flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
                root_url: '/uploads/articles'
                cache_prefix: media/cache
                visibility: public

    cache: articles_flysystem_resolver

    loaders:
        articles_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
    data_loader: articles_flysystem_loader

    filter_sets:
        article_preview:
            quality: 75
            filters:
                thumbnail: { size: [ 240, 240 ], mode: outbound }
        article_detail:
            quality: 75
            filters:
                thumbnail: { size: [ 480, 480 ], mode: outbound }